### ISSUE TITLE
Error during installation at step cache:clear

### ISSUE THREAD

**Issue by TrueXakeP** [FluffyDiscord/roadrunner-symfony-bundle#12]
Hello.
First sorry for my English.
I'm trying to start my first project with RoadRunner using Symfony. And when I'm trying to install this bundle and then do any other installs with composer I'm getting an error in `FluffyDiscordRoadRunnerExtension.php line 51` that saying I'm trying to auto register RoadRunner KV cache without installing the corresponding package.
To get the error I did nothing more than:
1. `symfony new rr-test && cd rr-test`
2. `composer require spiral/roadrunner-cli`
3. `./vendor/bin/rr get-binary`
4. Answer `yes` to the proposal to create default ".rr.yaml" configuration
5. `composer require fluffydiscord/roadrunner-symfony-bundle`
6. Get [KO] at cache:clear

Later I found that it is happening because of `kv:` configuration lines presence in the received default .rr.yaml and the error is gone when I delete them. But is it such important to get the lines removed at first place from the default configuration before start using this runtime? Or should I just not take this bundle for my first project with RR?

**Comment by FluffyDiscord** [comment]
@TrueXakeP hello, the behaviour is expected

This package does not rely on KV cache, but auto-registers the cache adapters if it finds them defined in .rr.yaml.

You are free to either:
1. Install the KV package as [exception explains](https://github.com/FluffyDiscord/roadrunner-symfony-bundle/blob/master/src/DependencyInjection/FluffyDiscordRoadRunnerExtension.php#L51)
2. Remove KV definition from .rr.yaml
3. Disable auto cache registration, as explained in [README](https://github.com/FluffyDiscord/roadrunner-symfony-bundle/blob/master/README.md?plain=1#L80) in `fluffy_discord_road_runner.yaml`
```yaml
fluffy_discord_road_runner:
  kv:
    auto_register: false
```

I recommend reading README explaining important things about this package at least once, to be aware what it can do or what are it's or symfony limitations.

I would be happy if you continue using my bundle and report back any issues you find (I am using it in all my projects, but there still might be things to be solved)

**Comment by TrueXakeP** [comment]
I apologize. Apparently I didn't read the README carefully enough. I'll be more careful in the future.
